version: '3.1'

services:
  db:
    image: linuxserver/mariadb:latest
    container_name: yourls-db
    networks:
      - yourls-isolated
    restart: unless-stopped
    volumes:
      - yourls-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=yourls
      - MYSQL_USER=yourls_user
      - MYSQL_PASSWORD=
      - TZ=Asia/Jakarta

  yourls:
    image: yourls:latest
    container_name: yourls-main
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - yourls-isolated
      - external
    expose:
      - 8080
    environment:
      - YOURLS_SITE=https://short.sayaingin.top
      - YOURLS_USER=scriber
      - YOURLS_PASS=
      - YOURLS_DB_HOST=db
      - YOURLS_DB_USER=yourls_user
      - YOURLS_DB_PASS=
    labels:
      - traefik.enable=true
      - traefik.http.routers.yourls.tls=true
      - traefik.http.routers.yourls.tls.certresolver=lets-encrypt
      - traefik.http.routers.yourls.rule=Host(`short.sayaingin.top`)

networks:
  external:
    external: true
  yourls-isolated:
    driver: bridge

volumes:
  yourls-db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/pi/Services/yourls/db'
