version: '3.1'

services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser 
    user: "1000:1000"
    command:
      - "-d=/srv/database.db"
      - "--cache-dir=/srv/cache"
    restart: unless-stopped
    expose:
      - 8080
    volumes:
      - filebrowser-data:/srv
    networks:
      - external
    environment:
      - APPLICATION_URL=https://sayaingin.top
    labels:
      - traefik.enable=true
      - traefik.http.routers.filebrowser.tls=true
      - traefik.http.routers.filebrowser.tls.certresolver=lets-encrypt
      - traefik.http.routers.filebrowser.rule=Host(`sayaingin.top`)

networks:
  external:
    external: true

volumes:
  filebrowser-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/data/sync'
