version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: miniflux-db 
    networks:
      - miniflux-isolated
    restart: unless-stopped
    volumes:
      - miniflux-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=th3AllS33ingEye5
      - POSTGRES_USER=miniflux
    labels:
      - traefik.enable=false

  app:
    image: miniflux/miniflux:latest
    container_name: miniflux-main
    restart: unless-stopped
    depends_on:
      - db
    expose:
      - 8080
    dns:
      - 172.18.0.1
    networks:
      - miniflux-isolated
      - external
    environment:
      - DATABASE_URL=postgres://miniflux:th3AllS33ingEye5@db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=heimdall
      - ADMIN_PASSWORD=Inf0rm4tionVaul7
      - BASE_URL=https://news.sayaingin.top
    labels:
      - traefik.enable=true
      - traefik.http.routers.miniflux.tls=true
      - traefik.http.routers.miniflux.tls.certresolver=lets-encrypt
      - traefik.http.routers.miniflux.rule=Host(`news.sayaingin.top`)
      - traefik.http.routers.miniflux.entrypoints=web, websecure

networks:
  external:
    external: true
  miniflux-isolated:
    driver: bridge

volumes:
  miniflux-db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/pi/Services/miniflux/db'
