version: "3.5"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    depends_on:
      - cloudflared
    networks:
      external:
      pihole-isolated:
        ipv4_address: 192.168.1.3
    environment:
      - TZ=Asia/Jakarta
      - WEBPASSWORD=zY!V8y7hAtePLp
      - PIHOLE_DNS_=192.168.1.2;8.8.8.8
      - VIRTUAL_HOST=hole.sayaingin.top
    volumes:
      - './pihole/:/etc/pihole/'
      - './dnsmasq.d/:/etc/dnsmasq.d/'
    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole.tls=true
      - traefik.http.routers.pihole.tls.certresolver=lets-encrypt
      - traefik.http.routers.pihole.rule=Host(`hole.sayaingin.top`)
      - traefik.http.routers.pihole.service=pihole
      - traefik.http.services.pihole.loadbalancer.server.port=80
      # 53 UDP
      - traefik.udp.routers.pihole-dns-udp.entrypoints=dns-udp
      - traefik.udp.routers.pihole-dns-udp.service=pihole-dns-udp
      - traefik.udp.services.pihole-dns-udp.loadbalancer.server.port=53
       # 53/tcp
      - traefik.tcp.routers.pihole-dns-tcp.rule=HostSNI(`*`)
      - traefik.tcp.routers.pihole-dns-tcp.entrypoints=dns-tcp
      - traefik.tcp.routers.pihole-dns-tcp.service=pihole-dns-tcp
      - traefik.tcp.services.pihole-dns-tcp.loadbalancer.server.port=53

  cloudflared:
    image: crazymax/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    expose:
      - 53
    networks:
      pihole-isolated:
        ipv4_address: 192.168.1.2
    environment:
      - "TZ=Asia/Jakarta"
      - TUNNEL_DNS_PORT=53

networks:
  external:
    external: true
  pihole-isolated:
    ipam:
      config:
        - subnet: 192.168.1.0/29
